name: test_regression_model
channels:
  - conda-forge
  - defaults
dependencies:
  - pandas=1.3.5
  - pip=22.3.1
  - mlflow=2.0.1
  - scikit-learn=0.24.1
  - pip:
      - wandb==0.13.7
      - git+https://github.com/Mamoutou7/build-ml-pipeline-for-short-term-rental-prices.git#egg=wandb-utils&subdirectory=components